import { NavComponent } from "@/components/navbar";
import React from "react";
import { getDictionary } from "./dictionaries";
import { LanguagesDictionary } from "@/types/dictionary";
import { Poppins } from "next/font/google";
import { Footer } from "@/components/footer";

import type { Metadata } from "next";

import "../globals.css";

interface IAllPagesLayout {
  children: React.ReactNode;
  params: {
    lang: string;
  };
}

export const metadata: Metadata = {
  title: "Big Balls",
  description: "Generated by create next app",
};

const poppins = Poppins({
  weight: ["300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
  display: "swap",
});

export default async function AllPagesLayout({
  children,
  params: { lang },
}: IAllPagesLayout) {
  const dict: LanguagesDictionary = await getDictionary(lang);
  return (
    <html lang={lang} className={`dark ${poppins.className}`}>
      <body className="bg-background">
        <NavComponent lang={lang} dict={dict} />
        {children}
        <Footer />
      </body>
    </html>
  );
}
