import { DashboardNavComponent } from "@/components/dashboard-nav";
import React from "react";
import { getDictionary } from "./dictionaries";
import { LanguagesDictionary } from "@/types/dictionary";

import type { Metadata } from "next";

import "../globals.css";

export const metadata: Metadata = {
  title: "Big Balls",
  description: "Generated by create next app",
};

interface IAllPagesLayout {
  children: React.ReactNode;
  params: {
    lang: string;
  };
}

export default async function AllPagesLayout({
  children,
  params: { lang },
}: IAllPagesLayout) {
  const dict: LanguagesDictionary = await getDictionary(lang);
  return (
    <html lang={lang}>
      <body>
        <DashboardNavComponent lang={lang} dict={dict} />
        {children}
      </body>
    </html>
  );
}
