import { DashboardNavComponent } from "@/components/dashboard-nav";
import React from "react";
import { getDictionary } from "./dictionaries";
import { LanguagesDictionary } from "@/types/dictionary";
import { League_Gothic } from "next/font/google";

import type { Metadata } from "next";

import "../globals.css";
import { Footer } from "@/components/footer";

interface IAllPagesLayout {
  children: React.ReactNode;
  params: {
    lang: string;
  };
}

export const metadata: Metadata = {
  title: "Big Balls",
  description: "Generated by create next app",
};

const leagueGothic = League_Gothic({
  weight: "400",
  subsets: ["latin"],
  display: "swap",
});

export default async function AllPagesLayout({
  children,
  params: { lang },
}: IAllPagesLayout) {
  const dict: LanguagesDictionary = await getDictionary(lang);
  return (
    <html lang={lang} className={`dark ${leagueGothic.className}`}>
      <body>
        <DashboardNavComponent lang={lang} dict={dict} />
        {children}
        <Footer />
      </body>
    </html>
  );
}
